### ISSUE TITLE
how use it

### ISSUE THREAD

**Issue by Yanbuodiao** [my-codeworks/tiff-viewer-extension#1]
Is there a demo to show how to use it

**Comment by d-Pixie** [comment]
Right now you have to clone it, open chrome and add it as a developer extension. See https://developer.chrome.com/extensions/getstarted#unpacked for how to add it as a developer extension in chrome.

If I had gotten it approved by the customer at the time I would have added it to the chrome store as a proper extension. If you find it useful I can add it to the web store and you can simple install it from there as with any other extension.

PS. Sorry for the long delayed answer. I have been on parental leave for 6 months and am just getting back in the swing of things 🙁

**Comment by d-Pixie** [comment]
Added to the marketplaces of both Chrome and Firefox. See the top of the README for links.
