### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by Pheil** [my-codeworks/tiff-viewer-extension#2]
Do you plan on uploading to Mozilla addons?

**Comment by d-Pixie** [comment]
I can have a look at how much work it would be to port it if you want.

**Comment by Pheil** [comment]
I tested it on Firefox 54.0a2, but it should work on the release version too since I don't think there are any APIs used that aren't supported it.

**Comment by d-Pixie** [comment]
Added to Firefox marketplace, see README for details.
